const wrapper = document.querySelector('.wrapper');
const loginLink = document.querySelector('.login-link');
const registerLink = document.querySelector('.register-link');
const btnPopup = document.querySelector(".btnLogin-popup");
const btn2Popup = document.querySelector(".register-btn");
const close = document.querySelector(".icon-close");
registerLink.addEventListener('click',()=>{wrapper.classList.add('active')});
loginLink.addEventListener('click',()=>{wrapper.classList.remove('active')});
btnPopup.addEventListener('click',()=>{wrapper.classList.add('active-popup')});
btnPopup.addEventListener('click',()=>{wrapper.classList.remove('active')});
close.addEventListener('click',()=>{wrapper.classList.remove('active-popup')});
/*btn2Popup.addEventListener('click',()=>{wrapper.classList.add('active')});
btn2Popup.addEventListener('click',()=>{wrapper.classList.add('active-popup')});*/